#pragma once

#include <cstdint>

#include <cuda_runtime_api.h>

#include "icecarver/case_config.h"

namespace icecarver {

// Generates nx * ny * nz float32 samples directly on the GPU. Coordinates are
// normalized independently to [-1, 1] on every axis. The same configuration
// and seed produce the same field on the contest image.
cudaError_t GenerateField(const CaseConfig& config, std::uint64_t variant_seed,
                          float* device_volume, cudaStream_t stream);

// SplitMix64 is used only to derive independent per-run seeds. The actual
// per-voxel random perturbation is generated by a fixed integer hash on device.
std::uint64_t DeriveVariantSeed(std::uint64_t case_seed,
                                std::uint64_t variant_index);

}  // namespace icecarver
